<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>8034ce09-b44b-48bc-8b9a-1ddc41c9b1c0</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add a new Response where
		the ClientID is "" , 
		the Message is "Please Provide Client ID" to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
